name: push image
on:
  push:
    branch:
         - python-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: docker login
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: docker build
        run: docker build -t techmypassion/python-app:latest .

      - name: push image
        run: docker push techmypassion/python-app:latest
           

